// ===========================================================================
// Copyright (c) 2018, Electric Power Research Institute (EPRI)
// All rights reserved.
//
// DLMS-COSEM ("this software") is licensed under BSD 3-Clause license.
//
// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:
//
// *  Redistributions of source code must retain the above copyright notice, this
//    list of conditions and the following disclaimer.
//
// *  Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//
// *  Neither the name of EPRI nor the names of its contributors may
//    be used to endorse or promote products derived from this software without
//    specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
// INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
// OF SUCH DAMAGE.
//
// This EPRI software incorporates work covered by the following copyright and permission
// notices. You may not use these works except in compliance with their respective
// licenses, which are provided below.
//
// These works are provided by the copyright holders and contributors "as is" and any express or
// implied warranties, including, but not limited to, the implied warranties of merchantability
// and fitness for a particular purpose are disclaimed.
//
// This software relies on the following libraries and licenses:
//
// ###########################################################################
// Boost Software License, Version 1.0
// ###########################################################################
//
// * asio v1.10.8 (https://sourceforge.net/projects/asio/files/)
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
// 

#pragma once

#include "appdefs.h"

#define DL_UNIT_DATA    0x00   // connectionless data transmission w/o ack.
#define DL_DATA_ACK     0x01   // connectionless data transmission with ack.
#define DL_DATA         0x02   // connection-oriented data transmission.

#define DL_IDLE              0
#define DL_CONNECTED         1
#define DL_RESET             2

//LLC type 3 commands
#define ACn 0xE6

#define is_ACn(cmd) ((cmd & ACn)==ACn)
#define    sqc(cmd) (cmd & 0x01)

#define Invalid_command 0xFF

// Status
#define _OK 0x00
#define _UN 0x09
#define _RS 0x08
#define _UE 0x0A
#define _PE 0x06

/*----------------------------------------------------------------------*/
//Selected HDLC subset + LLC type 1&2  commands
#define _SABM 0xF4   // with P=1
#define _UA   0xCE   // with F=1
#define _I_P  0x08   // information frame with P=1,NS=NR=0
#define _I    0x00   // information frame with P=0,NS=NR=0
#define __UI   0xC8   // Unumbered information with P=1
#define _RR   0x88   // RR command with F=1
#if 0
//Error Code
#define HDLC_FAILURE 20
#define ERROR_TRANS_DATA 21
#endif
/*----------------------------------------------------------------------*/

/*------------- Logical symbols for MAC sublayer services --------------*/
#define MA_UNIT_DATA    0x00  // connectionless data transmission w/o ack.
#define MA_SYNC_ACQ     0x01  // Synchronisation Acquisition
/*----------------------------------------------------------------------*/

/*----------------------------------------------------------------------*/
#define MAX_ADDR_SIZE    6   				// Max size in bytes for LSAP addresses
#define MAX_FRAME_SIZE   COMMDATA_MAXSIZE  	// Maximum Frame Size
#define MAC_PACKET       12  				// MAC Frame Size

