// ===========================================================================
// Copyright (c) 2018, Electric Power Research Institute (EPRI)
// All rights reserved.
//
// DLMS-COSEM ("this software") is licensed under BSD 3-Clause license.
//
// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:
//
// *  Redistributions of source code must retain the above copyright notice, this
//    list of conditions and the following disclaimer.
//
// *  Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//
// *  Neither the name of EPRI nor the names of its contributors may
//    be used to endorse or promote products derived from this software without
//    specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
// INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
// OF SUCH DAMAGE.
//
// This EPRI software incorporates work covered by the following copyright and permission
// notices. You may not use these works except in compliance with their respective
// licenses, which are provided below.
//
// These works are provided by the copyright holders and contributors "as is" and any express or
// implied warranties, including, but not limited to, the implied warranties of merchantability
// and fitness for a particular purpose are disclaimed.
//
// This software relies on the following libraries and licenses:
//
// ###########################################################################
// Boost Software License, Version 1.0
// ###########################################################################
//
// * asio v1.10.8 (https://sourceforge.net/projects/asio/files/)
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
// 

#include <gtest/gtest.h>

#include "../../lib/DLMS-COSEM/APDU/AARE.cpp"

using namespace EPRI;

static const std::vector<uint8_t> FINAL = 
{ 
    0x61, 0x29, 0xA1, 0x09, 0x06, 0x07, 0x60, 0x85, 0x74, 0x05, 0x08, 0x01, 0x01, 0xA2, 0x03, 0x02,
    0x01, 0x00, 0xA3, 0x05, 0xA1, 0x03, 0x02, 0x01, 0x00, 0xBE, 0x10, 0x04, 0x0E, 0x08, 0x00, 0x06,
    0x5F, 0x1F, 0x04, 0x00, 0x00, 0x38, 0x1F, 0x00, 0x9B, 0x00, 0x07
};


TEST(AARE, Build) 
{
    AARE                a1;
    ASNObjectIdentifier ApplicationContext({ 2, 16, 756, 5, 8, 1, 1 });
    
    ASSERT_TRUE(a1.application_context_name.Append(ApplicationContext));
    //
    // Just the application_context_name does not make a valid AARE...
    //
    ASSERT_FALSE(a1.IsValid());
       
    std::vector<uint8_t> A1CHECK_CONTEXT_NAME = 
    { 0xA1, 0x09, 0x06, 0x07, 0x60, 0x85, 
        0x74, 0x05, 0x08, 0x01, 0x01 };
    ASSERT_TRUE(a1.application_context_name == A1CHECK_CONTEXT_NAME);

    ASSERT_TRUE(a1.result.Append(int8_t(AARE::AssociationResult::accepted)));
    std::vector<uint8_t> A1CHECK_RESULT = 
        { 0xA2, 0x03, 0x02, 0x01, 0x00 };
    ASSERT_TRUE(a1.result == A1CHECK_RESULT);
    
    ASSERT_TRUE(a1.result_source_diagnostic.SelectChoice(AARE::AssociateDiagnosticChoice::acse_service_user));
    ASSERT_TRUE(a1.result_source_diagnostic.Append(int8_t(AARE::AssociateDiagnosticUser::user_null)));
    std::vector<uint8_t> A1CHECK_DIAGNOSTIC = 
    { 0xA3, 0x05, 0xA1, 0x03, 0x02, 0x01, 0x00 };
    ASSERT_TRUE(a1.result_source_diagnostic == A1CHECK_DIAGNOSTIC);
 
    ASSERT_TRUE(a1.user_information.Append(DLMSVector({ 0x08, 0x00, 0x06, 0x5F, 0x1F, 0x04, 
                                                        0x00, 0x00, 0x38, 0x1F, 0x00, 0x9B, 0x00, 0x07 })));
    std::vector<uint8_t> AARE_VEC = a1.GetBytes();
    ASSERT_TRUE(AARE_VEC == FINAL);
    
}

TEST(AARE, Parse) 
{
    AARE        a1;
    DLMSVector  Data(FINAL);
    
    ASSERT_TRUE(a1.Parse(&Data, 1, 1));
    //
    // Let's validate what we have!
    //
    ASNObjectIdentifier ApplicationContext({ 2, 16, 756, 5, 8, 1, 1 });
    ASNType             Result(ASN::INTEGER, int8_t(AARE::AssociationResult::accepted));
    ASNType             Diagnostic(ASN::INTEGER, int8_t(AARE::AssociateDiagnosticUser::user_null));
    ASNType             UserInformation(ASN::OCTET_STRING, 
                                        DLMSVector({ 0x08, 0x00, 0x06, 0x5F, 0x1F, 0x04, 
                                                     0x00, 0x00, 0x38, 0x1F, 0x00, 0x9B, 0x00, 0x07 }));
    
    ASNType Current;
    ASSERT_EQ(ASNType::GetNextResult::VALUE_RETRIEVED, a1.application_context_name.GetNextValue(&Current));
    ASSERT_TRUE(ApplicationContext == Current);
    
    DLMSValue Value1;
    ASSERT_EQ(ASNType::GetNextResult::VALUE_RETRIEVED, a1.result.GetNextValue(&Value1));
    ASSERT_FALSE(IsSequence(Value1));
    ASSERT_EQ(DLMSValueGet<int8_t>(Value1), int8_t(AARE::AssociationResult::accepted));

    
    //    ASN_BEGIN_SCHEMA(AARE::Associate_Source_Diagnostic_Schema)
    //        ASN_BEGIN_CHOICE
    //            ASN_BEGIN_CHOICE_ENTRY(acse_service_user)
    //                ASN_INTEGER_LIST_TYPE
    //                (   
    //                    ASN::CONSTRUCTED, 
    //                    { 
    //                        user_null, 
    //                        user_no_reason_given, 
    //                        application_context_name_not_supported,
    //                        authentication_mechanism_name_not_recognized,
    //                        authentication_mechanism_name_required,
    //                        authentication_failure,
    //                        authentication_required,
    //                    }
    //                )
    //            ASN_END_CHOICE_ENTRY
    //            ASN_BEGIN_CHOICE_ENTRY(acse_service_provider)
    //                ASN_INTEGER_LIST_TYPE
    //                (   
    //                    ASN::CONSTRUCTED, 
    //                    { 
    //                        provider_null, 
    //                        provider_no_reason_given, 
    //                        no_common_acse_version,
    //                    }
    //                )
    //            ASN_END_CHOICE_ENTRY
    //        ASN_END_CHOICE
    //    ASN_END_SCHEMA

    // Loop until we get a value... or fail...
    //
    int8_t Choice;
    ASSERT_EQ(ASNType::GetNextResult::VALUE_RETRIEVED, a1.result_source_diagnostic.GetNextValue(&Value1));
    ASSERT_TRUE(a1.result_source_diagnostic.GetChoice(&Choice));
    ASSERT_EQ(AARE::AssociateDiagnosticChoice::acse_service_user, Choice);
    ASSERT_EQ(DLMSValueGet<int8_t>(Value1), int8_t(AARE::AssociateDiagnosticUser::user_null));
    //
    // We should be at the end of the schema...
    //
    ASSERT_EQ(ASNType::GetNextResult::END_OF_SCHEMA, a1.result_source_diagnostic.GetNextValue(&Value1));
    a1.result_source_diagnostic.Rewind();
    ASSERT_FALSE(a1.result_source_diagnostic.GetChoice(&Choice));
    //
    // After Rewind, we should be able to get the value again...
    //
    ASSERT_EQ(ASNType::GetNextResult::VALUE_RETRIEVED, a1.result_source_diagnostic.GetNextValue(&Value1));
    ASSERT_TRUE(a1.result_source_diagnostic.GetChoice(&Choice));
    ASSERT_EQ(AARE::AssociateDiagnosticChoice::acse_service_user, Choice);
    ASSERT_EQ(DLMSValueGet<int8_t>(Value1), int8_t(AARE::AssociateDiagnosticUser::user_null));
   
    ASSERT_EQ(ASNType::GetNextResult::VALUE_RETRIEVED, a1.user_information.GetNextValue(&Current));
    ASSERT_TRUE(UserInformation == Current);
    

}
